### ISSUE TITLE
get age range from summary of BchronCalibrate

### ISSUE THREAD

**Issue by benmarwick** [andrewcparnell/Bchron#1]
Very often I need a table that has information about radiocarbon dates that includes the 95% calibrated range in the form or an upper and lower range values. 

It would be great it we could have a function that takes the output of `BchronCalibrate` and gives a data frame of the first two cols of each row of each date in the `summary` output .

For example, from https://cran.r-project.org/web/packages/Bchron/vignettes/Bchron.html

```
ages3 = BchronCalibrate(ages=c(3445,11553), 
                        ageSds=c(50,230), 
                        positions=c(100,150), 
                        calCurves=c('intcal13','normal'))
summary(ages3)
## Highest density regions for date1 
##       [,1]   [,2]   [,3]   [,4]   [,5]   [,6]
## 99% 3563.9 3870.0     NA     NA     NA     NA
## 95% 3590.0 3833.6     NA     NA     NA     NA
## 50% 3641.0 3670.7 3678.2 3723.2 3796.4 3816.5
## 
## Highest density regions for date2 
##        [,1]    [,2]
## 99% 10973.0 12133.0
## 95% 11099.0 12007.0
## 50% 11402.5 11703.5
```

I'd like something that gives a data frame like this that I can join to others:

|date | HDR_95_upper | HDR_95_lower |
| ---- |---- | --- |
| date1 | 3563.9 | 3870.0 | 
| date2 | 10973.0 | 12007 |

Currently I'm doing this:

```
  # show tables of calibrated age ranges for each date
  ages_HDR <- capture.output(summary(ages))

  # each date is six items, so split them into each date
  ages_HDR_list <-  split(ages_HDR, ceiling(seq_along(ages_HDR)/6))

  # 95 HDR upper and lower is 4th item of each date
  ages_HDR_values <- sapply(ages_HDR_list, function(i) i[4])

  # remove 95% and NAs
  removal <- c("95%", "NA")
  ages_HDR_values <-  gsub(paste(removal, collapse = "|"), "", ages_HDR_values)

  # 95 HDR is the first numeric (after 95%) and the last numeric
  df <- data.frame(upper = 1:length(ages_HDR_values),
                   lower = 1:length(ages_HDR_values))
  for(i in 1:length(ages_HDR_values)){
    tmp_1 <- strsplit(ages_HDR_values[i], split=" ")[[1]]
    tmp_2 <- tmp_1[tmp_1 != ""]
    tmp_upper <- as.numeric(tmp_2[length(tmp_2)])
    tmp_lower <- as.numeric(tmp_2[1])
    df[i,] <- c(tmp_upper, tmp_lower)
  }

# df is a data frame where each row is a date and col1 is the upper 95% and col2 is the lower 95%
```

This is too hacky to go in your excellent package, but something like it might be useful to other users.

What do you think?

thanks!

**Comment by andrewcparnell** [comment]
Hi Ben,

Thanks for using Bchron. It sounds like you want something different than Highest Density Regions. HDRs are meant to give multiple ranges for multi-modal probability distributions like calibrated radiocarbon dates. If you want a single interval you could do what you're doing above, but my guess is that this is no longer a 95% interval. Instead you might like to try the quantile function to produce a _credible interval_ rather than an HDR. 

For example, following your code above:

```
# First create age samples for each date
age_samples = lapply(ages3,function(x) sample(x$ageGrid,size=2000,replace=TRUE,prob=x$densities))
# Now summaries them with quantiles - this gives a 95% credible interval
lapply(age_samples,quantile,prob=c(0.025,0.975))
```

Certainly something like this could go into Bchron if it was desired.

**Comment by benmarwick** [comment]
Hi Andrew,

Thanks very much, that's really very helpful, and much simpler than my proposal. Perhaps it could be added to the vignette? It seems too short to be it's own function in the package. I would use `plyr::ldply` in place of `lapply` in your example, to get a data.frame as output.

**Comment by andrewcparnell** [comment]
Yes you're right, or even`sapply' to give you a matrix. Saves loading in another package!

I'll add it to the github vignette.
