### ISSUE TITLE
Output of predicted positions at depth = 0 with & without extractDate

### ISSUE THREAD

**Issue by orb16** [andrewcparnell/Bchron#10]
Hi there,

Bchron is the first choice in our group for age-depth modelling due to the ease of using an R package. During a recent group session we came up with a query about the format of the data that is returned by `summary.BchronologyRun`, particularly when an extractionDate is specified.  

If we seek the predicted positions for a core and include depth = 0, and include a normal calCurve for depth = 0 (ie as for the Glendalough example data), it seems odd that the predicted positions return age = 0 (even when the extractDate is specified as a year that is not the current one). 

This means in the summary output the columns have two different types of data in (one for depth = 0 where the normal curve is used, and the other for all other depths), and no column specifying which type of age is given in each row. 

Reprex below

```r
require(Bchron)
require(dplyr)
require(tidyr

data(Glendalough)

# without extract date
# means it defaults to 2018 for date of extraction
GlenOut = Bchronology(ages=Glendalough$ages,ageSds=Glendalough$ageSds,
                      calCurves=Glendalough$calCurves,
                      positions=Glendalough$position,
                      positionThicknesses=Glendalough$thickness,ids=Glendalough$id,
                      predictPositions=seq(0,1500,by=10))

# with extract date (should be extractAge)
GlenOut2 = Bchronology(ages=Glendalough$ages,ageSds=Glendalough$ageSds,
                      calCurves=Glendalough$calCurves,positions=Glendalough$position,
                      positionThicknesses=Glendalough$thickness,ids=Glendalough$id,
                      predictPositions=seq(0,1500,by=10),
                      extractDate = 1950 - 2000) # pretend date of 2000 for extraction

out1 <- summary(GlenOut) %>% select(Depth, `50%`) %>% 
mutate(type = "No extract date") %>% 
select(type, everything())

out2 <- summary(GlenOut2) %>% select(Depth, `50%`) %>% 
mutate(type = "With extract date") %>% 
select(type, everything())

allOut <- bind_rows(out1, out2)%>% spread(type, `50%`)

# both first rows give a different type of data to that of the others
# but also, shouldn't the extract date affect the first row? 
# sometimes you get 0, 0, other times 1, 0, but close enough
head(allOut)
```

It would be good to know the workflow that is expected for users to come up with data that's all in the same age format? I was wondering whether it would be better to supply all the output in the same age format (accompanied by appropriate documentation)?

We've studied the documentation and vignette but have been unable to figure it out. 

Kind regards,

Olivia

**Comment by andrewcparnell** [comment]
Hi Olivia,

Sorry for the delay in replying. Haven't been checking Bchron issues very often!

When I ran your code I got the following (yours might not be identical due to the stochastic part of the model fitting):
```
> head(allOut)
  Depth No extract date With extract date
1     0             0.0                 0
2    10            59.5                62
3    20           119.0               124
4    30           178.0               186
5    40           235.5               247
6    50           288.0               309
```
I'm not sure what you mean by 'both first rows give a different type of data to that of the others'. The results are different because the `extractDate` will constrain the interpolated chronologies and remove those which go beyond the specified value. Not sure if that answers your question but perhaps you can come back with more detail in case I've misunderstood.

Andrew
