### ISSUE TITLE
plot, withPositions

### ISSUE THREAD

**Issue by allisonstegner** [andrewcparnell/Bchron#11]
Hello,

Just a note to let you know that there is a typo in the help documentation for BchronCalibrate. The help page in R says that plot(ages3,withDepths=TRUE) will plot the calibrated densities against depth. This does not work, but (ages3,withPositions=TRUE) does. I found the correct information at https://cran.r-project.org/web/packages/Bchron/vignettes/Bchron.html

Best regards,
Allison

**Comment by andrewcparnell** [comment]
Thanks Allison. Fixed in latest update!
