### ISSUE TITLE
Occasional Bchronology error

### ISSUE THREAD

**Issue by taphocoenose** [andrewcparnell/Bchron#13]
Hello,

I have been running the Bchronology function across 32 datasets, and occasionally, the function fails and I receive warning and error messages:

_Error in if (stats::runif(1) < exp(logRpsi)) psi = psiNew : 
  missing value where TRUE/FALSE needed
In addition: Warning message:
In log(dtweediep1(diff(theta[do]), p, mu * diffPosition, psiNew/(diffPosition)^(p -  :
  NaNs produced_

This seems to occur randomly, as any one of the 32 runs generally succeeds and returns the function results. Across the 32 datasets, Bchronology will return this error for anywhere from 0 to 4 of them (the datasets for which it fails changes during each time I apply it across the 32 datasets).

At the moment, I have implemented some error catching code to simply rerun the failed attempts until they succeed, but this is not optimal.

Thanks
Ryan

**Comment by andrewcparnell** [comment]
Hi Ryan,

Sorry to hear this. I'd be interested to know the data sets that are causing it to fail. You might like to put something like `set.seed(123)` at the top of your script so that all the results are repeatable. Then we find out which ones are causing problems. It's likely something to do with dates/depths out of order.

Andrew

**Comment by taphocoenose** [comment]
Hi Andrew,

I can certainly provide some code. The R script for all 32 datasets is a little long due to data preprocessing, so I have reduced it to two examples for one of the 32 datasets. This single-dataset examples produce the above described error.

The first example is a loop that repeatedly attempts to fit an age-depth model to the dataset. I get ~1-2 errors for every 10 attempts.

```r
library(Bchron)

set.seed(86082)

# Data for Bchronology arguments
dates <- data.frame(labID=c("GrA-49570", "GrA-49521", "GrA-49516", 
                            "GrA-49507", "GrA-49527", "GrA-49529", 
                            "GrA-49573", "GrA-49574", "GrA-49569", 
                            "GrA-49514", "GrA-49575", "GrA-49515", 
                            "GrA-49509", "GrA-49524"),
                    age=c(10735, 10765, 10765, 10920, 10960, 10755, 
                          10860, 10845, 10895, 10880, 10900, 11020, 
                          10865, 10840),
                    error=c(45, 50, 50, 50, 60, 55, 45, 45, 45, 
                            110, 50, 75, 55, 75),
                    depth=c(1.5, 1.5, 7, 7, 7, 7, 7, 7, 9, 9, 9.25, 
                            10.75, 10.75, 10.75),
                    thickness=c(1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2.5, 
                                1.5, 1.5, 1.5))

predPositions <- seq(from=min(dates$depth),
                     to=max(dates$depth),
                     length.out=300)

# Attempt to fit the same Bchron age-depth model
# multiple times.
for(i in 1:30){
  
  try(
    
    attempt <- Bchronology(ages=dates$age,
                           ageSds=dates$error,
                           positions=dates$depth,
                           positionThicknesses=dates$thickness,
                           calCurves=rep("intcal13", nrow(dates)),
                           ids=dates$labID,
                           outlierProbs=rep(0.1, nrow(dates)),
                           predictPositions=predPositions,
                           jitterPositions=T,
                           iterations=9000, 
                           burn=4000, thin=5)
    
  )
  
  if(exists("attempt")){
    cat("\nBchronology success\n")
    rm(attempt)
  }else{
    cat("\nBchronology error\n")
  }

}
```

The chance of encountering an error seems to increase with larger values for the iterations argument. For the second example, I used the same dataset with iterations increased from 9000 to 104,000. I switched to a parallel lapply function to save some time, as sampling time obviously increases. Here, I get errors for about 50% of models.

```r
library(Bchron)
library(parallel)

set.seed(86082)

# Data for Bchronology arguments
dates <- data.frame(labID=c("GrA-49570", "GrA-49521", "GrA-49516", 
                            "GrA-49507", "GrA-49527", "GrA-49529", 
                            "GrA-49573", "GrA-49574", "GrA-49569", 
                            "GrA-49514", "GrA-49575", "GrA-49515", 
                            "GrA-49509", "GrA-49524"),
                    age=c(10735, 10765, 10765, 10920, 10960, 10755, 
                          10860, 10845, 10895, 10880, 10900, 11020, 
                          10865, 10840),
                    error=c(45, 50, 50, 50, 60, 55, 45, 45, 45, 
                            110, 50, 75, 55, 75),
                    depth=c(1.5, 1.5, 7, 7, 7, 7, 7, 7, 9, 9, 9.25, 
                            10.75, 10.75, 10.75),
                    thickness=c(1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2.5, 
                                1.5, 1.5, 1.5))

predPositions <- seq(from=min(dates$depth),
                     to=max(dates$depth),
                     length.out=300)

# Create cluster
cores <- detectCores() - 1
cl <- makeCluster(cores)
clusterExport(cl=cl, varlist=list("dates", "predPositions"))
clusterEvalQ(cl, library("Bchron"))

# Attempt to fit the same Bchron age-depth model
# multiple times. If it is unsuccessful, return
# an object indicating lack of success. Otherwise,
# return the model.
Bchronology_attempts <- parLapply(cl, 1:8, function(x){
  
  try(
    
    attempt <- Bchronology(ages=dates$age,
                           ageSds=dates$error,
                           positions=dates$depth,
                           positionThicknesses=dates$thickness,
                           calCurves=rep("intcal13", nrow(dates)),
                           ids=dates$labID,
                           outlierProbs=rep(0.1, nrow(dates)),
                           predictPositions=predPositions,
                           jitterPositions=T,
                           iterations=104000, 
                           burn=4000, thin=100)
    
  )
  
  if(!exists("attempt")){
    attempt <- "Bchronology error"
  }
  
  return(attempt)
  
})

stopCluster(cl)
```
There are a number of repeated depth values in this dataset, perhaps that's an issue? Hopefully I am not overlooking something obvious, I only started using the Bchronology function recently.

I am using R 3.6.1 in RStudio 1.2.5001 on a Windows 10 machine. Bchron 4.3.0.

Thanks!

Ryan

**Comment by andrewcparnell** [comment]
Hi Ryan. OK had a look through. The reason this error occurs is because the underlying code keeps running into a numerical underflow where the difference between depths get very close to zero. This can happen when there are a lot of dates at similar depths. 

There is a quick fix! You can simply include `positionScaleVal = 1` in your call to `Bchronology` and everything should run fine (it did for me). I'll have a think about how better I can remove this error or add a warning as to what to change if others run into it.

Let me know if this doesn't work (or you run into other problems).

Andrew

**Comment by taphocoenose** [comment]
This appears to have cleared it up for me, thanks!

Ryan

**Comment by QuinnAsena** [comment]
Hello,

I have run into the same error but without the small depth differences... In my case the data are simulated. Found this thread while trying to solve the issue, `positionScaleVal = 1` does not seem to have solved it for me.

Hope the following example can help! 

Thanks!
Quinn

`#The data

chron_df <- structure(list(sim_time = c(4750L, 4501L, 4001L, 3501L, 3001L, 
2501L, 2001L, 1501L, 1001L, 501L, 1L), sim_acc_rate = c(0, 1, 
1, 1, 1, 1, 1, 1, 1, 1, 1), labID = c("id_ 4750", "id_ 4501", 
"id_ 4001", "id_ 3501", "id_ 3001", "id_ 2501", "id_ 2001", "id_ 1501", 
"id_ 1001", "id_ 501", "id_ 1"), sim_depth = c(0L, 249L, 749L, 
1249L, 1749L, 2249L, 2749L, 3249L, 3749L, 4249L, 4749L), sim_age = c(0, 
249, 749, 1249, 1749, 2249, 2749, 3249, 3749, 4249, 4749), sim_age_round = c(0, 
249, 749, 1249, 1749, 2249, 2749, 3249, 3749, 4249, 4749), error = c(10, 
47, 62, 57, 70, 59, 64, 59, 57, 72, 69), calCurves = c("normal", 
"normal", "normal", "normal", "normal", "normal", "normal", "normal", 
"normal", "normal", "normal")), row.names = c(NA, -11L), class = c("tbl_df", 
"tbl", "data.frame"))`

`set.seed(1984) #works without issue

set.seed(2049) #gets to 24%

chronOut1 = with(chron_df, 
               Bchronology(ages=sim_age_round,
                           ageSds=error, 
                           calCurves=calCurves,
                           positions=sim_depth,
                           ids=labID,
                           positionScaleVal = 1))
`

R R version 3.6.1, R studio Version 1.3.615, Windows 10,

**Comment by andrewcparnell** [comment]
Sorry it's taken so long to get back to this - a really trick bug to fix. Should be done now in the latest development version of Bchron. (You'll need to do `devtools::install_github('andrewcparnell/Bchron')` to get it). 

In case you care what was happening it was to do with chronologies which were completely straight (like your example above) which causes the parameter controlling the variability in the chronology to go to zero and hence crash. 

Your code above now runs for me but I can't promise to have fixed all possible chronologies! Let me know if you find any more, and thanks again for pointing this out.

Andrew

**Comment by QuinnAsena** [comment]
Thanks very much for getting back to me, much appreciated. 

I suspected it was running into some zero values when browsing the underlying calculation where the error occurred but didn't realise it was a result of the linear sedimentation model (good to know!).

I'll do some more work using the latest development (and different sedimentation rates) and let you know if the error re-occurs!

Thanks again,
Quinn
