### ISSUE TITLE
Weird age-depth models

### ISSUE THREAD

**Issue by kbh022** [andrewcparnell/Bchron#16]
Hi,

I am trying to plot age-depth models, but getting a bit weird plots although the data looks fine. 
I am attaching here an example-dataset  and the code I used. Any suggestion on this would be of great help!

Best wishes,
Kuber

[example_dataset.xlsx]
[example_output.pdf](https://github.com/andrewcparnell/Bchron/files/4428415/example_output.pdf)
(https://github.com/andrewcparnell/Bchron/files/4428339/example_dataset.xlsx)
[example_code.txt](https://github.com/andrewcparnell/Bchron/files/4428426/example_code.txt)

**Comment by andrewcparnell** [comment]
Thanks for this - replied to you over email but updated version now on GitHub.
