### ISSUE TITLE
Feature request: smoothed output in plot

### ISSUE THREAD

**Issue by cmbarton** [andrewcparnell/Bchron#19]
While I've been using numMix to reduce the complexity in BchronDensity results, it might be better to use some kind of window smoother, like a running mean, as an option.

**Comment by andrewcparnell** [comment]
Thanks cmbarton - nummix is meant to be the smoother. Adding a smoother here would essentially change (and possibly invalidate) the model.

**Comment by cmbarton** [comment]
OK. If it is truly a smoother, that's fine. The docs aren't very clear on that and I worried that I was using it the wrong way.

**Comment by cmbarton** [comment]
Here is a graphic produced by bchron where the SPD curve is very obscured by the individual date curves. 

![SPD_with_dates](https://user-images.githubusercontent.com/8967599/101185605-5269b200-360f-11eb-97d7-cc078d44e2d3.png)
