### ISSUE TITLE
wish: create vectors of date and densities for total density curve of BchronDensity

### ISSUE THREAD

**Issue by cmbarton** [andrewcparnell/Bchron#2]
Bchron is a really useful package for R. I appreciate your efforts in making this available. This "issue" is a wish for future releases.

BchronDensityFast objects include the data points for the summed probabilities curve as...

bchronobject$out$data and bchronobject$out$density

This makes it possible to easily plot results in another graphics package, like ggplot. Both BchronDensity and BchronDensityFast have the points (dates and densities) for each of the calibrated dates that make up the summed total curve, so that these can be plotted in other packages. But BchronDensity does not seem to generate the data points for the total curve the way that BchronDensityFast does. It would be nice if this could be added a future release of Bchron.

**Comment by willrath** [comment]
Excellent point! Have you looked at the plot.BchronDensityRun function? If
you look at the source code on gitHub:

plot.BchronDensityRun on gitHub
<https://github.com/cran/Bchron/blob/master/R/plot.BchronDensityRun.R>

you will see on lines 31 - 33:

31: densFinal = dens/sum(dens)
32:
33: graphics::plot(dateGrid,densFinal,type='l',ylab='Density',ylim=range(c(0
,densFinal)),...)

This is the step that actually creates the smoothed line that is plotted
for the final SRPD plot. The object 'dens' is the vector of summed
probability splines at each age step through your range of calibrated
dates. densFinal is the same but has been normalized to sum to 1, making it
a valid density object. The plotting call is included to show you how to
set up the x axis for plotting outside of the function. Please let me know
if you need further help, thanks for the question. I can also write an
argument for plot.BchronDensityRun that will cause the function to also
return the vector that you're asking for.

**Comment by cmbarton** [comment]
Thanks William,

Andrew sent me to plot.BchronDensityRun after I wrote him directly, and also noted the issues page here on GitHub. 

Line 33 is a straightforward plot command, but getting the variables to be plotted is a more complicated process, of parsing through a couple of matrices, doing some transformations on intermediate results, and putting the pieces together. So I was wishing that BchronDensity could output the vectors dateGrid and densFinal. Or perhaps it is easier to do this from plot.BchronDensityRun, which would be equally useful. 

Cheers
Michael

**Comment by willrath** [comment]
Michael,

No problem at all, I understand your suggestion more clearly now. The
BchronDensity object does have to go through the plot.BchronDensityRun
function to be assembled into the type of line you get from the
BchronDensityFast function and plot call. I usually copy and paste the
plot.BchronDensityRun function into a scripting window, assign it as a
function in my global environment, and run the function line-by-line (with
my BchronDensity object named x) until I get to densFinal = dens/sum(dens).
At that point I have both densFinal and dateGrid in my global environment
and can plot them or write them to tables or pass to other packages. This
will create a 1 column matrix object for both densFinal and dateGrid, you
might want to double check that the object class will plot how you want
given the packages you intend to use. It is important to run the function
line by line to get the objects into the global environment, once the last
} is close the objects won't be available.

I am also working on a few "convenience-type" suggestions for Bchron that
will include yours and a few other tweaks, I'll make sure you're notified
when they go up. I hope this helps for now, let me know if I can help
further.

Thanks,

Will

**Comment by cmbarton** [comment]
Thanks much. Great package.

____________________
C. Michael Barton
Director, Center for Social Dynamics & Complexity
Professor of Anthropology, School of Human Evolution & Social Change
Head, Graduate Faculty in Complex Adaptive Systems Science
Arizona State University

voice:  480-965-6262 (SHESC), 480-965-8130/727-9746 (CSDC)
fax: 480-965-7671 (SHESC),  480-727-0709 (CSDC)
www: http://www.public.asu.edu/~cmbarton, http://csdc.asu.edu






On Feb 11, 2016, at 8:54 PM, William Rath <notifications@github.com<mailto:notifications@github.com>> wrote:

Michael,

No problem at all, I understand your suggestion more clearly now. The
BchronDensity object does have to go through the plot.BchronDensityRun
function to be assembled into the type of line you get from the
BchronDensityFast function and plot call. I usually copy and paste the
plot.BchronDensityRun function into a scripting window, assign it as a
function in my global environment, and run the function line-by-line (with
my BchronDensity object named x) until I get to densFinal = dens/sum(dens).
At that point I have both densFinal and dateGrid in my global environment
and can plot them or write them to tables or pass to other packages. This
will create a 1 column matrix object for both densFinal and dateGrid, you
might want to double check that the object class will plot how you want
given the packages you intend to use. It is important to run the function
line by line to get the objects into the global environment, once the last
} is close the objects won't be available.

I am also working on a few "convenience-type" suggestions for Bchron that
will include yours and a few other tweaks, I'll make sure you're notified
when they go up. I hope this helps for now, let me know if I can help
further.

Thanks,

Will

**Comment by andrewcparnell** [comment]
Hi All,

Apologies - seem to have missed these comments amongst all the others I get. Let me know if this is still unresolved.

**Comment by cmbarton** [comment]
Unless you guys have release a new version, nothing has changed.

Michael

**Comment by andrewcparnell** [comment]
Hi Michael,

Apologies for taking so long over this. I've just added in an extra optional argument `store_density` to the `BchronDensity` function which hopefully stores the object you need. You'll need to install the github version of the package via `devtools::install_github('andrewcparnell/Bchron') to get at it.

Let me know if you run into any problems.

Andrew

**Comment by cmbarton** [comment]
Whoohoo!! Thanks much. I've got some papers coming up soon where this will be helpful. 

Cheers
Michael Barton

**Comment by cmbarton** [comment]
Andrew,

Just tried it. The help says that for a BchronDensity object BDO, I should be able to get BDO$density, but it doesn't seem to exist when I try to look at it. 


Michael Barton

**Comment by cmbarton** [comment]
I missed a step. I do get the densities now. But there are no ages to plot with them that I can see


Michael Barton

**Comment by andrewcparnell** [comment]
Hi Michael,

The code I used for the example data is as follows:

devtools::install_github('andrewcparnell/Bchron')
library(Bchron)

data(Sluggan)
SlugDens = BchronDensity(ages=Sluggan$ages,
                         ageSds=Sluggan$ageSds,
                         calCurves=Sluggan$calCurves,
                         numMix=50,
                         store_density=TRUE)

plot(SlugDens$age_grid,SlugDens$density,type='l')


Let me know if that works for you.

Andrew

-------------------------------
Andrew Parnell CStat
Senior Lecturer in Statistics	
School of Mathematics and Statistics
University College Dublin
Tel: (+353) 1 716 2422
mathsci.ucd.ie/~parnell_a/ <http://mathsci.ucd.ie/~parnell_a/>

**Comment by cmbarton** [comment]
This did it. Thanks.


Michael Barton
