### ISSUE TITLE
Feature request: SPD should plot on top of individual data polygons

### ISSUE THREAD

**Issue by cmbarton** [andrewcparnell/Bchron#20]
For better visualization, the SPD curve should plot on top of (after) the individual data polygons. Currently, a lot of date polygons obscure the SPD curve, even though they are semi-transparent, because they plot over the curve.

**Comment by andrewcparnell** [comment]
This sounds like a good idea. Would it be possible to share a picture/code of what you had in mind (or where it's going wrong?)

Andrew

**Comment by cmbarton** [comment]
Hi Andrew,

I only just now saw this notification. I'll do a graphic and show you.

**Comment by cmbarton** [comment]
Here is a graphic produced by bchron where the SPD curve is very obscured by the individual date curves.

![SPD_with_dates](https://user-images.githubusercontent.com/8967599/101186363-36b2db80-3610-11eb-8135-42e4586c3873.png)

**Comment by andrewcparnell** [comment]
OK that makes sense. It's a bit of a fiddly fix because I don't a reproducible example. However I've updated the GitHub code so you should be able to try it out now. Here's some sample code you could run:
```
library(remotes)
install_github('andrewcparnell/Bchron')
library(Bchron)
data(Sluggan)
SlugDens = BchronDensity(ages=Sluggan$ages,
                         ageSds=Sluggan$ageSds,
                         calCurves=Sluggan$calCurves,
                         iterations = 100,
                         burn = 20,
                         thin = 1)
plot(SlugDens)
```
I've also enabled the ability to change the transparency level of the dates:
```
plot(SlugDens, dateTransparency = 0.2)
```

**Comment by cmbarton** [comment]
Thanks much. It's sort of an insane week, but I look forward to trying it out soon.
