### ISSUE TITLE
Possible to expose an argument so we can adjust the size of dateLabels?

### ISSUE THREAD

**Issue by benmarwick** [andrewcparnell/Bchron#22]
I'd love to adjust the size of `dateLabels` text on my plots. I see you are using [geom_text](https://github.com/andrewcparnell/Bchron/blob/f7748af09db032eb64d128b25c1129e9039deffb/R/plot.BchronCalibratedDates.R#L275) for those. I don't think we can modify any parameters for that outside of that function (unlike the axes, which we can mod with `scale_y_` etc.). Would it be possible to have a `dateLabelsSize` that maps to `geom_text(size = dateLabelsSize)`? Thank you!

**Comment by andrewcparnell** [comment]
Sorry for the delay - missed this issue for some reason. There is now an argument `dateLabelSize` in the plotting functions for `BChronology` and `BchronCalibrate` that allows you to adjust the size of the date labels as requested. It's only in the GitHub/development version for now but will be added to the CRAN version next time I update. 

Thanks for the suggestion!

**Comment by benmarwick** [comment]
Thank you very much for considering this request!
