### ISSUE TITLE
plot.BchronologyRun not recognizing normal plot arguments

### ISSUE THREAD

**Issue by cmbarton** [andrewcparnell/Bchron#23]
Hi Andy. Beginning in some recent version plot.BchronologyRun stopped recognizing standard plot arguments xlab, ylab, main, and cex. 

It also does not seem to be producing a plot object that is recognized by subsequent plot commands like abline or axis. When these are run immediately after plot.BchronologyRun, it generates the error: "plot.new has not been called yet". So there is no way to modify the plot. 

I updated to bchron 4.7.5 and R 4.0.5 and have the newest Mac OS.

**Comment by andrewcparnell** [comment]
Hi Michael,

Apologies this changed a few versions ago but I don't think I documented it well. You can customise the plots by adding on standard `ggplot2` commands. Here's a reproducible example:

```
library(Bchron)
library(ggplot2)
data(Glendalough)
GlenOut = with(Glendalough, 
               Bchronology(ages=ages,
                           ageSds=ageSds, 
                           calCurves=calCurves,
                           positions=position, 
                           positionThicknesses=thickness,
                           ids=id, 
                           predictPositions=seq(0,1500,by=10)))
plot(GlenOut) +
  labs(title = "Glendalough",
       xlab = "Age (cal years BP)",
       ylab = "Depth (cm)")
```

I've updated the documentation and the manual to make this clearer.

**Comment by cmbarton** [comment]
Thanks. ggplot2 commands will be very nice. Is this the case for all bchron plots now?

**Comment by andrewcparnell** [comment]
It is for the functions which use ggplot2, which I think is all of them apart from `plot.BchronDensityRun`. One day I'll get round to improving that function too.

**Comment by andrewcparnell** [comment]
Doubly well spotted!
