### ISSUE TITLE
Providing Delta R and error values for calibrating marine samples?

### ISSUE THREAD

**Issue by IanMoffat** [andrewcparnell/Bchron#26]
Hi @andrewcparnell,
Thanks for the fantastic package!  I'm wondering if it is possible to specify Delta R (and error values) when calibrating marine samples in Bchron?  If not, can I suggest this as a future enhancement please?
Many thanks,
Ian

**Comment by andrewcparnell** [comment]
Hi Ian. You're not the first person to ask me about this, so I've put a potential solution in the online manual [here](
http://andrewcparnell.github.io/Bchron/articles/Bchron.html#calibrating-marine-and-other-offset-age-ranges-1).

Let me know if that helps.

Andrew

**Comment by andrewcparnell** [comment]
Hi Ian. This is a query I've got a few times which I think perhaps is quite simple and doesn't need any extra commands. I've put it in the manual [here](https://andrewcparnell.github.io/Bchron/articles/Bchron.html#calibrating-marine-and-other-offset-age-ranges-1). Have a look and get back to me if it doesn't make sense. 

Andrew

**Comment by IanMoffat** [comment]
Many thanks Andrew, I'm not sure how I missed this in the manual previously but that is exactly the solution I need!  Much appreciated!
