### ISSUE TITLE
wish: changes to "position" plotting in BchronCalibrate

### ISSUE THREAD

**Issue by cmbarton** [andrewcparnell/Bchron#3]
Plotting a BchronCalibrate object creates very nice looking plots of calibrated date probability curves in stratigraphic sequence if the argument "withPostions=TRUE" is specified. However, it assumes the position variable always represents depth below surface. It then reverses the y-coordinate to ensure that the largest position number is at the origin and the smallest is at the top of the graph. 

However, in many archaeological excavations--and some other contexts too--depositional units are numbered from the bottom up (e.g., 1 is at the bottom and 10 is at the top). These could be an arbitrary sequence (or set of strings) or elevation above or below a site datum point. Trying to flip the y-axis back (e.g., using ylim), so that the smallest number is at the origin and largest is at the top of the graph, raises an error. It would be nice if there were a flag to turn off the y-coordinate reversal. 

As implied above, depositional units also are often identified by strings instead of by real numbers (e.g., "Unit 2B"). So it would also be nice if BchronCalibrate could accept a vector of strings as well as real numbers for the "position=" argument.

Finally, to be even better, I'd suggest that there be separate "position" and "label" arguments. Both would be optional. Position with no labels, would arrange the calibration curves according to their distance along a specified real-number position vector (e.g., like depth, but with the option of turning off the default y-coordinate flip and below surface assumption). Labels with no position, would arrange the curves at evenly spaced intervals, in order of a specified label vector, and use the label vector to label each curve. Positions and labels would arrange the curves vertically according to a real number position (depth below surface or elevation above/below a datum) and label them with the label vector values. No position and no label would operate as now when the position argument is left at NULL. 

Thanks
Michael Barton

**Comment by andrewcparnell** [comment]
Hi Michael,

I've just updated the plotting function in Bchron so that you have a bit more control over the axes and their labels and directions. Try out the new version and see if it gives you what you want.

Andrew

**Comment by cmbarton** [comment]
Thanks much Andrew. 

I will also pass this on to my colleagues who are using BChron here.


Michael Barton

**Comment by cmbarton** [comment]
Andrew,

I just did a quick test of the new BChron. I still don't see how to do a plot from BchronCalibrate by position with 0 and the bottom and 100 at the top of the y-axis. The plot.BchronCalibratedDates function flips the y axis on the plots so that bigger numbers are at the bottom and smaller numbers are at the top of the axis. This makes sense if the position is depth below surface, but not if position is relative to a fixed vertical datum whose 0 point if below current surface or sampling levels numbered from oldest to youngest. The way I normally flip the y-axis in standard R plots is using ylim. But the plot function already does this and I'm not permitted to flip it back. Perhaps I am missing something here.

**Comment by andrewcparnell** [comment]
Hi Michael,

Apologies - I updated the plot.Bchronology function to have this feature but not the plot.BchronCalibratedDates function. Have done so now so you should be able to fiddle with axis limits and labels.

Andrew

**Comment by cmbarton** [comment]
I’ve been trying BChron 4.2.1. Is that the latest? 

When plotting results from a BchronCalibrate run, I still can’t flip the either axis. I get:

Error in plot.default(1, 1, xlim = rev(xlimits), ylim = rev(ylimits),  : 
  formal argument "ylim" matched by multiple actual arguments

Michael

**Comment by cmbarton** [comment]
Maybe your revised version isn’t in CRAN yet? 

Cheers
Michael

**Comment by andrewcparnell** [comment]
That's odd. If I run:
```
ages1 = BchronCalibrate(ages=11553,
                        ageSds=230,
                        calCurves='intcal13',
                        ids='Date-1')
plot(ages1, xlim=c(15000,13000))
```
I get perfectly flipped axes?

Andrew

**Comment by cmbarton** [comment]
Thanks for checking on the Andrew. Your help in this is wonderful. Here is what happens, using one of the demo data sets.

> GDL.calib <- with(Glendalough, BchronCalibrate(ages = ages, ageSds = ageSds, calCurves = calCurves, ids = id, positions = position))
> plot(GDL.calib, withPositions = T, xlim = c(0, 14000), ylim = c(0, 1500))
Error in plot.default(1, 1, xlim = rev(xlimits), ylim = rev(ylimits),  : 
  formal argument "xlim" matched by multiple actual arguments

**Comment by cmbarton** [comment]
My wish on this is not only to be able to reverse the y-axis (highest priority for me), but to allow for string “positions” on the y-axis. This makes it possible to display the dates for a set of different archaeological sites arranged in order chronologically and with their probability polygons showing.  

For example, here is a nice graph, generated from BchronDensity for a series of human burials from a series of sites in eastern Spain, dating to the period just before and after the beginning of farming (red = pre-farming, green=earliest farmers, blue=slightly later farmers, grey=all burials together). Because of your recent updates, I am able to draw this in ggplot so all the curves can be combined like this.





I’d also like to do a nice plot of dates of all burials by site. But alas, I can only do that by giving the sites numbers that are treated as depths. And I can’t even change the title to say “Calibrated Dates of Burials by Site”. I can of course edit this after the fact in a drawing program. But to the extent I understand the code, it might not be too difficult to implement this in some future version.



Cheers
Michael

**Comment by andrewcparnell** [comment]
Hi Michael,

Bizarrely that command works for me on the GitHub version, installed with:
```
devtools::install_github('andrewcparnell/Bchron')
```
but not on the CRAN version (installed with `install.packages`). I'll update the CRAN version (to 4.2.2) but in the meantime feel free to use the GitHub version.

I'm not sure I follow your plotting request as the graph you mention doesn't seem to appear for me. 

Andrew

**Comment by cmbarton** [comment]
Thanks. I haven't been able to use the GitHub version because it requires R 3.3. But I've started updating my computers and should be able to compile it soon.

Here are dropbox links to the graphs I mentioned:

The summed probability curves from BchronDensity
https://www.dropbox.com/s/2n8kio0jmq5vj9v/summed_prob_dates.tiff?dl=0 <https://www.dropbox.com/s/2n8kio0jmq5vj9v/summed_prob_dates.tiff?dl=0> 

The burial dates by site from BchronCalibrate
https://www.dropbox.com/s/pqfmruug89r7bel/dates_by_site.tiff?dl=0 <https://www.dropbox.com/s/pqfmruug89r7bel/dates_by_site.tiff?dl=0> 

Michael

**Comment by andrewcparnell** [comment]
Nice plots!

If I understand you correctly, you can do what you want by turning off the y-axis (using `yaxt='n'`) and then adding it in again, e.g.:
```
GDL.calib <- with(Glendalough, 
                  BchronCalibrate(ages = ages, 
                                  ageSds = ageSds, 
                                  calCurves = calCurves, 
                                  ids = id, 
                                  positions = position))
plot(GDL.calib, withPositions = T, yaxt='n')
axis(side=2, at = Glendalough$position, letters[1:6], las = 1)
```

**Comment by cmbarton** [comment]
Thanks for the code. It allowed me to get much closer to what I would like to do by assigning fake positions to sites.

See the graph at: https://www.dropbox.com/s/3xcf1eqqtqh9mpq/dates_by_site.png?dl=0 <https://www.dropbox.com/s/3xcf1eqqtqh9mpq/dates_by_site.png?dl=0>  so you can see how this could work with my wish for extending the position/ID functions.

Still stuck with the default graph title. But otherwise looks very good.

Michael

**Comment by andrewcparnell** [comment]
That looks great. You should be able to change the plot title with e.g.
```
plot(GDL.calib, withPositions = T, yaxt='n', main = 'Something else')
```

**Comment by cmbarton** [comment]
I wish. It gives me the same kind of error as trying to flip the axes. 

Error in plot.default(1, 1, xlim = rev(xlimits), ylim = rev(ylimits),  : 
  formal argument "main" matched by multiple actual arguments

Maybe with your new version (still working with 4.2.1 here).

Michael

**Comment by andrewcparnell** [comment]
Yes you'll need 4.2.2. It's up on CRAN now I think so you should be able to get it with `install.packages('Bchron')`. However, I don't think they've finished building for every operating system yet. Let me know if it works!

**Comment by cmbarton** [comment]
I just updated to 4.2.2 from source via CRAN

This code worked a few minutes ago:

VB.calib <- with(valencia.burials, BchronCalibrate(ages = uncal.mean, ageSds = uncal.sd, calCurves = calib.curve, ids = site.name, positions = site.num))
par(mar= c(5.1, 10.1, 4.1, 2.1))
plot(VB.calib, withPositions = T, ylab="", xlab="calibrated years BP", yaxt='n')
axis(side=2, at = unique(valencia.burials$site.num), labels = unique(valencia.burials$site.name), las = 1, tck=1, lwd.ticks = .5, lty = "dotted")
box()

Now, plot gives me this weird error

Error in plot.new() : outer margins too large (figure region too small)

I reset par to the default margins 
par(mar= c(5.1, 4.1, 4.1, 2.1))

And I get the same error

Michael

**Comment by andrewcparnell** [comment]
I think this is a bug in RStudio (are you using RStudio?) and is sometimes resolved by re-sizing the plot window. If not, you should just export your plots to a pdf file using the pdf command (or ggsave if using ggplot2).

**Comment by cmbarton** [comment]
I'm using RStudio.

I quit and restarted and no longer have that error. But check out the results of the same code (with the title working now).

VB.calib <- with(valencia.burials, BchronCalibrate(ages = uncal.mean, ageSds = uncal.sd, calCurves = calib.curve, ids = site.name, positions = site.num))
par(mar= c(5.1, 10.1, 4.1, 2.1))
plot(VB.calib, withPositions = T, ylab="", xlab="calibrated years BP", yaxt='n', main = "Calibrated Dates of Burials by Site")
axis(side=2, at = unique(valencia.burials$site.num), labels = unique(valencia.burials$site.name), las = 1, tck=1, lwd.ticks = .5, lty = "dotted")
box()

graph: https://www.dropbox.com/s/63oembchr5sss3o/dates_by_sites4.2.2.png?dl=0 <https://www.dropbox.com/s/63oembchr5sss3o/dates_by_sites4.2.2.png?dl=0> 

And with the y-axis reversed:

graph: https://www.dropbox.com/s/r9xdez93iju6hsh/dates_by_site4.2.2_yreversed.png?dl=0 <https://www.dropbox.com/s/r9xdez93iju6hsh/dates_by_site4.2.2_yreversed.png?dl=0>

**Comment by andrewcparnell** [comment]
Check out the `dateHeight` argument. If the axes are reversed you'll need to make it negative.

**Comment by cmbarton** [comment]
OK. That is what was wrong with the non-reversed one too. It looks like dateHeight is defaulting to 30. Too big for my data (1 is about right) and too small for Glendalough (100 is about right). I can set this with no problem and it does give nice control over the looks. How did v. 4.2.1 make such good default guesses on this?

Michael

**Comment by andrewcparnell** [comment]
In previous versions there was some fancier code to guess the date height but I dropped it once people could control the y-axis themselves, and set it to the default value of 30 which works OK for Glendalough and the other standard peat cores that most people use Bchron for.

**Comment by cmbarton** [comment]
Got it. Easy to manipulate once you know. 

Thanks again
Michael
