### ISSUE TITLE
Equivalent of Oxcal's phase & boundary

### ISSUE THREAD

**Issue by benmarwick** [andrewcparnell/Bchron#5]
I'd love to know if there's a way to use this package to get ages for the start and end of a phase .

With Oxcal we can use Phase() and Boundary() to estimate start and end dates of phases: https://c14.arch.ox.ac.uk/oxcalhelp/hlp_analysis_eg.html

It would be great if we could do this using this package.  We need these estimates often in archaeology. Is it currently possible with Bchron, or would it require substantial further work to enable?

Thanks!

**Comment by andrewcparnell** [comment]
Hi Ben,

The current non-parametric approach in Bchron (created via `BchronDensity` or `BchronDensityFast` doesn't have a parameter representing the start or end of a phase like the trapezoid or uniform phase models of Oxcal. One way to do it would be to calculate the 95% or 99% range of the density of the phase.

Currently this isn't very simple to do in Bchron with fiddling with a bit of internal code. But when I get a spare moment I'll put something in the GitHub version of Bchron and you can test it out.

Andrew

**Comment by benmarwick** [comment]
Hi Andrew,

Thanks for taking a look. I look forward to testing these enhancements!

best,

Ben

**Comment by andrewcparnell** [comment]
Hi Ben,

New version 4.2.5 of Bchron up on GitHub (and shortly on CRAN) which includes phase estimation for density models. An example is given in the [vignette](https://cran.r-project.org/web/packages/Bchron/vignettes/Bchron.html). See the section on running non-parametric phase estimation. 

Please test it out and report back if it's helpful or needs to be changed. 

Andrew
