### ISSUE TITLE
problem with marine13 calibration curve

### ISSUE THREAD

**Issue by cmbarton** [andrewcparnell/Bchron#6]
I'm trying to calibrate data from a Red Sea core and wanted to use the marine13 calibration curve. But when I do, I get this error, no matter what date range I'm using.

Error in BchronCalibrate(ages = years.BP.uncal, ageSds = SD, calCurves = calib.curve) : 
  Date Date1 outside of calibration range

All of my dates are less than 50k, and I get this error even with a subset between 100 and 1000 years. I get no error if I use the intcal13 curve. Any thoughts?

Michael Barton

**Comment by cmbarton** [comment]
I figured out that I have to cut off my date series at >400 BP. Not clear what the max cut off is, but 45ka seems to work OK.

**Comment by andrewcparnell** [comment]
Hi Michael. Apologies for missing this comment. This might be because the minimum age from the marine13 calibration curve (at http://www.radiocarbon.org/IntCal13%20files/marine13.14c) is 469 14C years BP.

**Comment by cmbarton** [comment]
Thanks Andrew,

It might be good to have the min/max calibration range for each curve mentioned in the docs. 

Michael Barton

**Comment by andrewcparnell** [comment]
Great minds think alike! Just added it in to the error message.

Andrew
