### ISSUE TITLE
Adding modern/bomb calibration?

### ISSUE THREAD

**Issue by lconners** [andrewcparnell/Bchron#7]
Hi Andrew--

I've been trying to add the Hua et al 2013 bomb radiocarbon calibration (NH2) to BChron-- I've converted from F14C to 14C ages and errors and am able to add the calibration text file using CreateCalCurves. However, when I try to use the curve I get the error:

Error in if (stats::runif(1) < exp(logRtheta)) theta[do[j]] = thetaNew : 
  missing value where TRUE/FALSE needed

I've used post-bomb dates in Bacon without issue, so I imagine I am doing something wrong in adding the calibratrion curve. Any help would be appreciated.

Another unrelated question-- is the vertical uncertainty (thickness) included in the calculation of age uncertainties when predicting ages from the  calculated age-depth model? 

Thanks,

Laura

**Comment by andrewcparnell** [comment]
Hi Laura,

Sorry to hear you're having problems. Bchron doesn't like sub-yearly resolutions on calibration curves so that might be one of the issues.

If that doesn't help I think the easiest way for me to help you is if you email me at andrew.parnell@ucd.ie with your data/code.

Andrew
