### ISSUE TITLE
Adding possibility to convert between calBC-calBP

### ISSUE THREAD

**Issue by Numaios** [andrewcparnell/Bchron#9]
Add a function, or similar, to convert calBP-calBC and viceversa.

**Comment by andrewcparnell** [comment]
Hi. Sorry I hadn't spotted this issue before. You can do this in the latest (development) version of Bchron. If you follow the vignette until you've created the object `GlenOut`, you can then run:

```
plot(GlenOut, ageScale = 'bc', scaleReverse = FALSE)
```

...and it should do the job.

**Comment by shheidgen** [comment]
hi! i am having trouble to plot my calibrated dates. I would be very thankful for help!
#MY CODE:

ages1=BchronCalibrate(ages=c(5850,6640,6845,6885,7170,7270,7360,7365,7560,7630,7780,6075,6865,7470,7870,7985,7990,8010,8020,8025,8090,8145,8160,8200,8225,8230,8235,8250,8285,8305,8315,8370,8495,8560,8640,8660,8710,8720,8730,8745,9450,5040,5450,7335,8195,8680,8705,8730,8710,8875,8940,9350,3545,3550),ageSds=c(85,65,80,65,70,75,80,75,40,95,80,100,100,95,80,95,70,75,80,95,80,65,65,65,65,65,75,70,90,65,80,70,70,85,70,90,65,85,90,65,120,60,100,90,65,75,75,70,90,75,75,90,45,55),calCurves=c("intcal13","intcal13","intcal13","intcal13","intcal13","intcal13","intcal13","intcal13","intcal13","intcal13","intcal13","intcal13","intcal13","intcal13","intcal13","intcal13","intcal13","intcal13","intcal13","intcal13","intcal13","intcal13","intcal13","intcal13","intcal13","intcal13", "intcal13", "intcal13", "intcal13", "intcal13", "intcal13", "intcal13", "intcal13", "intcal13","intcal13","intcal13","intcal13","intcal13","intcal13","intcal13","intcal13","intcal13","intcal13","intcal13","intcal13","intcal13","intcal13","intcal13","intcal13","intcal13","intcal13","intcal13","intcal13","intcal13"))


summary(ages1)

#THEN WHEN I TYPE THIS:
> plot(ages1)

# I GET THE ERROR MESSAGE:
Error in seq.default(my_hdr[[j]][1], my_hdr[[j]][2], by = 1) : 
  wrong sign in 'by' argument


i dont understand why i get this error, i though it was a bug. i am trying to creatr a curve with all my dates, where calBP is in X axis. afterwards i need to plot calBC vs calBP, as the C14 are from archaeological material, it doesnt have depths where i can related them to, only horiznts and this is not helpful for this case.

thanks in advanced!
